import dependencies

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

reading data

In [2]:
datafile_train=r'data/raw_data/carvan_train.csv'
datafile_test=r'data/raw_data/carvan_test.csv'
train=pd.read_csv(datafile_train)
test=pd.read_csv(datafile_test)

### Data processing

In [3]:
train.isnull().sum().sum(),test.isnull().sum().sum() # there are no missing values in the data

(0, 0)

In [4]:
train.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61',
       'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71',
       'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81',
       'V82', 'V83', 'V84', 'V85', 'V86'],
      dtype='object')

renaming based on data dict provided

In [5]:
train.rename(columns = { 'V1' : 'Customer Subtype',
                        'V2' : 'Number of houses',
                        'V3' : 'Avg size household',
                        'V4' : 'Avg age',
                        'V5' : 'Customer main type',
                        'V6' : 'Roman catholic',
                        'V7' : 'Protestant',
                        'V8' : 'Other religion',
                        'V9' : 'No religion',
                        'V10' : 'Married',
                        'V11' : 'Living together',
                        'V12' : 'Other relation',
                        'V13' : 'Singles',
                        'V14' : 'Household without children',
                        'V15' : 'Household with children',
                        'V16' : 'High level education',
                        'V17' : 'Medium level education',
                        'V18' : 'Lower level education',
                        'V19' : 'High status',
                        'V20' : 'Entrepreneur',
                        'V21' : 'Farmer',
                        'V22' : 'Middle management',
                        'V23' : 'Skilled labourers',
                        'V24' : 'Unskilled labourers',
                        'V25' : 'Social class A',
                        'V26' : 'Social class B1',
                        'V27' : 'Social class B2',
                        'V28' : 'Social class C',
                        'V29' : 'Social class D',
                        'V30' : 'Rented house',
                        'V31' : 'Home owners',
                        'V32' : 'MAUT1 1 car',
                        'V33' : 'MAUT2 2 cars',
                        'V34' : 'MAUT0 No car',
                        'V35' : 'National Health Service',
                        'V36' : 'Private health insurance',
                        'V37' : 'Income < 30.000',
                        'V38' : 'Income 30-45.000',
                        'V39' : 'Income 45-75.000',
                        'V40' : 'Income 75-122.000',
                        'V41' : 'Income >123.000',
                        'V42' : 'Average income',
                        'V43' : 'Purchasing power class',
                        'V44' : 'Contribution private third party insurance',
                        'V45' : 'Contribution third party insurance (firms)',
                        'V46' : 'Contribution third party insurane (agriculture)',
                        'V47' : 'Contribution car policies',
                        'V48' : 'Contribution delivery van policies',
                        'V49' : 'Contribution motorcycle/scooter policies',
                        'V50' : 'Contribution lorry policies',
                        'V51' : 'Contribution trailer policies',
                        'V52' : 'Contribution tractor policies',
                        'V53' : 'Contribution agricultural machines policies' ,
                        'V54' : 'Contribution moped policies',
                        'V55' : 'Contribution life insurances',
                        'V56' : 'Contribution private accident insurance policies',
                        'V57' : 'Contribution family accidents insurance policies',
                        'V58' : 'Contribution disability insurance policies',
                        'V59' : 'Contribution fire policies',
                        'V60' : 'Contribution surfboard policies',
                        'V61' : 'Contribution boat policies',
                        'V62' : 'Contribution bicycle policies',
                        'V63' : 'Contribution property insurance policies',
                        'V64' : 'Contribution social security insurance policies',
                        'V65' : 'Number of private third party insurance',
                        'V66' : 'Number of third party insurance (firms)',
                        'V67' : 'Number of third party insurane (agriculture)',
                        'V68' : 'Number of car policies',
                        'V69' : 'Number of delivery van policies',
                        'V70' : 'Number of motorcycle/scooter policies',
                        'V71' : 'Number of lorry policies',
                        'V72' : 'Number of trailer policies',
                        'V73' : 'Number of tractor policies',
                        'V74' : 'Number of agricultural machines policies',
                        'V75' : 'Number of moped policies',
                        'V76' : 'Number of life insurances',
                        'V77' : 'Number of private accident insurance policies',
                        'V78' : 'Number of family accidents insurance policies',
                        'V79' : 'Number of disability insurance policies',
                        'V80' : 'Number of fire policies',
                        'V81' : 'Number of surfboard policies',
                        'V82' : 'Number of boat policies',
                        'V83' : 'Number of bicycle policies',
                        'V84' : 'Number of property insurance policies',
                        'V85' : 'Number of social security insurance policies',
                        'V86' : 'CARAVAN Number of mobile home policies'}, 
             inplace = True)

In [6]:
test.rename(columns = { 'V1' : 'Customer Subtype',
                        'V2' : 'Number of houses',
                        'V3' : 'Avg size household',
                        'V4' : 'Avg age',
                        'V5' : 'Customer main type',
                        'V6' : 'Roman catholic',
                        'V7' : 'Protestant',
                        'V8' : 'Other religion',
                        'V9' : 'No religion',
                        'V10' : 'Married',
                        'V11' : 'Living together',
                        'V12' : 'Other relation',
                        'V13' : 'Singles',
                        'V14' : 'Household without children',
                        'V15' : 'Household with children',
                        'V16' : 'High level education',
                        'V17' : 'Medium level education',
                        'V18' : 'Lower level education',
                        'V19' : 'High status',
                        'V20' : 'Entrepreneur',
                        'V21' : 'Farmer',
                        'V22' : 'Middle management',
                        'V23' : 'Skilled labourers',
                        'V24' : 'Unskilled labourers',
                        'V25' : 'Social class A',
                        'V26' : 'Social class B1',
                        'V27' : 'Social class B2',
                        'V28' : 'Social class C',
                        'V29' : 'Social class D',
                        'V30' : 'Rented house',
                        'V31' : 'Home owners',
                        'V32' : 'MAUT1 1 car',
                        'V33' : 'MAUT2 2 cars',
                        'V34' : 'MAUT0 No car',
                        'V35' : 'National Health Service',
                        'V36' : 'Private health insurance',
                        'V37' : 'Income < 30.000',
                        'V38' : 'Income 30-45.000',
                        'V39' : 'Income 45-75.000',
                        'V40' : 'Income 75-122.000',
                        'V41' : 'Income >123.000',
                        'V42' : 'Average income',
                        'V43' : 'Purchasing power class',
                        'V44' : 'Contribution private third party insurance',
                        'V45' : 'Contribution third party insurance (firms)',
                        'V46' : 'Contribution third party insurane (agriculture)',
                        'V47' : 'Contribution car policies',
                        'V48' : 'Contribution delivery van policies',
                        'V49' : 'Contribution motorcycle/scooter policies',
                        'V50' : 'Contribution lorry policies',
                        'V51' : 'Contribution trailer policies',
                        'V52' : 'Contribution tractor policies',
                        'V53' : 'Contribution agricultural machines policies' ,
                        'V54' : 'Contribution moped policies',
                        'V55' : 'Contribution life insurances',
                        'V56' : 'Contribution private accident insurance policies',
                        'V57' : 'Contribution family accidents insurance policies',
                        'V58' : 'Contribution disability insurance policies',
                        'V59' : 'Contribution fire policies',
                        'V60' : 'Contribution surfboard policies',
                        'V61' : 'Contribution boat policies',
                        'V62' : 'Contribution bicycle policies',
                        'V63' : 'Contribution property insurance policies',
                        'V64' : 'Contribution social security insurance policies',
                        'V65' : 'Number of private third party insurance',
                        'V66' : 'Number of third party insurance (firms)',
                        'V67' : 'Number of third party insurane (agriculture)',
                        'V68' : 'Number of car policies',
                        'V69' : 'Number of delivery van policies',
                        'V70' : 'Number of motorcycle/scooter policies',
                        'V71' : 'Number of lorry policies',
                        'V72' : 'Number of trailer policies',
                        'V73' : 'Number of tractor policies',
                        'V74' : 'Number of agricultural machines policies',
                        'V75' : 'Number of moped policies',
                        'V76' : 'Number of life insurances',
                        'V77' : 'Number of private accident insurance policies',
                        'V78' : 'Number of family accidents insurance policies',
                        'V79' : 'Number of disability insurance policies',
                        'V80' : 'Number of fire policies',
                        'V81' : 'Number of surfboard policies',
                        'V82' : 'Number of boat policies',
                        'V83' : 'Number of bicycle policies',
                        'V84' : 'Number of property insurance policies',
                        'V85' : 'Number of social security insurance policies',
                        'V86' : 'CARAVAN Number of mobile home policies'}, 
             inplace = True)

combining train and test dataset for simultaneous preprocessing to the new dataset "all_data"

In [7]:
train['data']='train'
test['data']='test'
all_data=pd.concat([train,test],0,sort=False)

In [8]:
columns = all_data.columns
#columns

In [9]:
target = 'CARAVAN Number of mobile home policies'

In [10]:
# calculate corr coefficient 
# corr = train.corr()
# corr.style.background_gradient(cmap='coolwarm').set_precision(2)

# corr_df = train.corr(method ='pearson')
# corr_df[corr_df["CARAVAN Number of mobile home policies"]<0]["CARAVAN Number of mobile home policies"].sort_values()

In [11]:
def prob_table(data, col, y):
    print("*"*50)
    print("feature/column:", col)
    temp_data = pd.crosstab(index=data[y], 
                             columns=data[col],
                             margins=True)   # Include row and column totals

    cols = sorted(data[col].unique())
    cols.append("rowtotal")
    temp_data.columns = cols
    temp_data.index= ["0","1","coltotal"]

    print((temp_data/temp_data.loc["coltotal"]).round(2))
    print("*"*50)

In [12]:
columns = ['Customer Subtype', 'Number of houses', 'Avg size household', 'Avg age',
       'Customer main type', 'Roman catholic', 'Protestant', 'Other religion',
       'No religion', 'Married', 'Living together', 'Other relation',
       'Singles', 'Household without children', 'Household with children',
       'High level education', 'Medium level education',
       'Lower level education', 'High status', 'Entrepreneur', 'Farmer',
       'Middle management', 'Skilled labourers', 'Unskilled labourers',
       'Social class A', 'Social class B1', 'Social class B2',
       'Social class C', 'Social class D', 'Rented house', 'Home owners',
       'MAUT1 1 car', 'MAUT2 2 cars', 'MAUT0 No car',
       'National Health Service', 'Private health insurance',
       'Income < 30.000', 'Income 30-45.000', 'Income 45-75.000',
       'Income 75-122.000', 'Income >123.000', 'Average income',
       'Purchasing power class', 'Contribution private third party insurance',
       'Contribution third party insurance (firms)',
       'Contribution third party insurane (agriculture)',
       'Contribution car policies', 'Contribution delivery van policies',
       'Contribution motorcycle/scooter policies',
       'Contribution lorry policies', 'Contribution trailer policies',
       'Contribution tractor policies',
       'Contribution agricultural machines policies',
       'Contribution moped policies', 'Contribution life insurances',
       'Contribution private accident insurance policies',
       'Contribution family accidents insurance policies',
       'Contribution disability insurance policies',
       'Contribution fire policies', 'Contribution surfboard policies',
       'Contribution boat policies', 'Contribution bicycle policies',
       'Contribution property insurance policies',
       'Contribution social security insurance policies',
       'Number of private third party insurance',
       'Number of third party insurance (firms)',
       'Number of third party insurane (agriculture)',
       'Number of car policies', 'Number of delivery van policies',
       'Number of motorcycle/scooter policies', 'Number of lorry policies',
       'Number of trailer policies', 'Number of tractor policies',
       'Number of agricultural machines policies', 'Number of moped policies',
       'Number of life insurances',
       'Number of private accident insurance policies',
       'Number of family accidents insurance policies',
       'Number of disability insurance policies', 'Number of fire policies',
       'Number of surfboard policies', 'Number of boat policies',
       'Number of bicycle policies', 'Number of property insurance policies',
       'Number of social security insurance policies',
       'CARAVAN Number of mobile home policies']
for col in columns:
    prob_table(train, col, 'CARAVAN Number of mobile home policies')

**************************************************
feature/column: Customer Subtype
            1     2    3     4     5    6     7     8     9    10  ...    33  \
0         0.9  0.93  0.9  0.96  0.96  0.9  0.93  0.85  0.96  0.95  ...  0.94
1         0.1  0.07  0.1  0.04  0.04  0.1  0.07  0.15  0.04  0.05  ...  0.06
coltotal  1.0  1.00  1.0  1.00  1.00  1.0  1.00  1.00  1.00  1.00  ...  1.00

            34    35    36    37    38    39   40    41  rowtotal
0         0.95  0.96  0.93  0.92  0.93  0.94  1.0  0.98      0.94
1         0.05  0.04  0.07  0.08  0.07  0.06  0.0  0.02      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.00      1.00

[3 rows x 41 columns]
**************************************************
**************************************************
feature/column: Number of houses
             1     2    3    4    5    6    7    8   10  rowtotal
0         0.94  0.93  1.0  1.0  1.0  1.0  1.0  1.0  1.0      0.94
1         0.06  0.07  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.0  1.0  1.0  1.0  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Avg size household
             1     2     3     4     5  rowtotal
0         0.97  0.95  0.94  0.93  0.94      0.94
1         0.03  0.05  0.06  0.07  0.06      0.06
coltotal  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Avg age
             1     2     3     4     5     6  rowtotal
0         0.99  0.94  0.94  0.94  0.94  0.97      0.94
1         0.01  0.06  0.06  0.06  0.06  0.03      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Customer main type
             1     2     3    4     5     6     7     8     9    10  rowtotal
0         0.91  0.87  0.93  1.0  0.97  0.98  0.96  0.94  0.94  0.98      0.94
1         0.09  0.13  0.07  0.0  0.03  0.02  0.04  0.06  0.06  0.02      0.06
coltotal  1.00  1.00  1.00  1.0  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Roman catholic
             0     1     2     3     4     5     6    7    8    9  rowtotal
0         0.95  0.93  0.93  0.95  0.98  0.94  0.92  1.0  1.0  1.0      0.94
1         0.05  0.07  0.07  0.05  0.02  0.06  0.08  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Protestant
             0     1     2     3     4     5     6    7     8     9  rowtotal
0         0.99  0.96  0.94  0.95  0.95  0.94  0.95  0.9  0.95  0.95      0.94
1         0.01  0.04  0.06  0.05  0.05  0.06  0.05  0.1  0.05  0.05      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Other religion
             0     1     2     3     4     5  rowtotal
0         0.94  0.95  0.93  0.93  0.95  0.96      0.94
1         0.06  0.05  0.07  0.07  0.05  0.04      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: No religion
             0     1     2     3     4     5     6     7    8    9  rowtotal
0         0.92  0.91  0.93  0.94  0.95  0.95  0.98  0.91  1.0  1.0      0.94
1         0.08  0.09  0.07  0.06  0.05  0.05  0.02  0.09  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Married
             0     1     2     3     4     5     6     7     8     9  rowtotal
0         0.97  0.99  0.98  0.98  0.97  0.95  0.94  0.93  0.93  0.92      0.94
1         0.03  0.01  0.02  0.02  0.03  0.05  0.06  0.07  0.07  0.08      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Living together
             0     1     2     3     4    5    6    7  rowtotal
0         0.93  0.94  0.95  0.96  0.99  1.0  1.0  1.0      0.94
1         0.07  0.06  0.05  0.04  0.01  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Other relation
             0     1     2     3     4     5     6     7    8     9  rowtotal
0         0.92  0.94  0.94  0.94  0.96  0.98  0.98  0.98  1.0  0.96      0.94
1         0.08  0.06  0.06  0.06  0.04  0.02  0.02  0.02  0.0  0.04      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.00      1.00
**************************************************
**************************************************
feature/column: Singles
             0     1     2     3     4     5     6     7     8    9  rowtotal
0         0.93  0.93  0.94  0.95  0.96  0.95  0.97  0.99  0.96  1.0      0.94
1         0.07  0.07  0.06  0.05  0.04  0.05  0.03  0.01  0.04  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Household without children
             0     1     2     3     4     5     6     7     8     9  rowtotal
0         0.94  0.94  0.95  0.94  0.94  0.95  0.92  0.92  0.93  0.97      0.94
1         0.06  0.06  0.05  0.06  0.06  0.05  0.08  0.08  0.07  0.03      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Household with children
             0     1     2     3     4     5     6     7     8     9  rowtotal
0         0.97  0.97  0.94  0.94  0.94  0.95  0.93  0.93  0.91  0.92      0.94
1         0.03  0.03  0.06  0.06  0.06  0.05  0.07  0.07  0.09  0.08      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: High level education
             0     1     2     3     4     5     6     7     8     9  rowtotal
0         0.96  0.94  0.94  0.93  0.89  0.89  0.88  0.88  0.91  0.89      0.94
1         0.04  0.06  0.06  0.07  0.11  0.11  0.12  0.12  0.09  0.11      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Medium level education
             0     1     2     3     4     5     6     7     8     9  rowtotal
0         0.97  0.94  0.95  0.94  0.94  0.93  0.95  0.89  0.92  0.91      0.94
1         0.03  0.06  0.05  0.06  0.06  0.07  0.05  0.11  0.08  0.09      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Lower level education
            0     1    2     3     4     5     6     7     8     9  rowtotal
0         0.9  0.89  0.9  0.93  0.94  0.95  0.96  0.96  0.95  0.98      0.94
1         0.1  0.11  0.1  0.07  0.06  0.05  0.04  0.04  0.05  0.02      0.06
coltotal  1.0  1.00  1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: High status
             0     1     2     3     4     5     6     7     8     9  rowtotal
0         0.95  0.95  0.94  0.93  0.92  0.95  0.87  0.85  0.88  0.94      0.94
1         0.05  0.05  0.06  0.07  0.08  0.05  0.13  0.15  0.12  0.06      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Entrepreneur
             0     1     2     3     4     5  rowtotal
0         0.94  0.93  0.93  0.92  0.92  0.94      0.94
1         0.06  0.07  0.07  0.08  0.08  0.06      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Farmer
             0     1     2     3     4     5    6    7    8    9  rowtotal
0         0.93  0.96  0.96  0.96  0.99  0.98  1.0  1.0  1.0  1.0      0.94
1         0.07  0.04  0.04  0.04  0.01  0.02  0.0  0.0  0.0  0.0      0.06

coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Middle management
             0     1     2     3     4     5     6     7    8    9  rowtotal
0         0.95  0.95  0.94  0.95  0.94  0.92  0.92  0.88  1.0  0.9      0.94
1         0.05  0.05  0.06  0.05  0.06  0.08  0.08  0.12  0.0  0.1      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Skilled labourers
             0     1     2     3     4     5     6     7     8    9  rowtotal
0         0.93  0.91  0.94  0.96  0.96  0.96  0.96  0.93  0.88  0.9      0.94
1         0.07  0.09  0.06  0.04  0.04  0.04  0.04  0.07  0.12  0.1      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Unskilled labourers
             0     1     2     3     4     5     6     7     8    9  rowtotal
0         0.92  0.92  0.94  0.95  0.95  0.95  0.95  0.97  0.89  1.0      0.94
1         0.08  0.08  0.06  0.05  0.05  0.05  0.05  0.03  0.11  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Social class A
             0     1     2     3     4     5     6     7     8    9  rowtotal
0         0.95  0.95  0.94  0.93  0.89  0.89  0.88  0.84  0.92  1.0      0.94
1         0.05  0.05  0.06  0.07  0.11  0.11  0.12  0.16  0.08  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Social class B1
             0     1     2     3     4     5    6    7     8    9  rowtotal
0         0.95  0.95  0.94  0.92  0.94  0.95  0.8  1.0  0.88  1.0      0.94
1         0.05  0.05  0.06  0.08  0.06  0.05  0.2  0.0  0.12  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.0  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Social class B2
             0     1     2     3     4     5     6    7    8    9  rowtotal
0         0.94  0.95  0.94  0.94  0.93  0.95  0.94  1.0  1.0  1.0      0.94
1         0.06  0.05  0.06  0.06  0.07  0.05  0.06  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Social class C
             0     1     2     3     4     5     6     7     8     9  rowtotal
0         0.93  0.89  0.92  0.94  0.95  0.96  0.94  0.95  0.89  0.95      0.94
1         0.07  0.11  0.08  0.06  0.05  0.04  0.06  0.05  0.11  0.05      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Social class D
             0     1     2     3     4     5     6     7    9  rowtotal
0         0.93  0.94  0.95  0.97  0.98  0.99  0.95  0.92  1.0      0.94
1         0.07  0.06  0.05  0.03  0.02  0.01  0.05  0.08  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Rented house
            0     1     2     3     4     5     6     7     8     9  rowtotal
0         0.9  0.91  0.95  0.93  0.95  0.95  0.94  0.96  0.97  0.96      0.94
1         0.1  0.09  0.05  0.07  0.05  0.05  0.06  0.04  0.03  0.04      0.06
coltotal  1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Home owners
             0     1     2     3     4     5     6     7     8    9  rowtotal
0         0.96  0.97  0.96  0.94  0.95  0.95  0.94  0.95  0.91  0.9      0.94
1         0.04  0.03  0.04  0.06  0.05  0.05  0.06  0.05  0.09  0.1      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: MAUT1 1 car
            0    1     2     3     4     5     6     7     8     9  rowtotal
0         1.0  1.0  0.98  0.97  0.97  0.95  0.95  0.92  0.93  0.92      0.94
1         0.0  0.0  0.02  0.03  0.03  0.05  0.05  0.08  0.07  0.08      0.06
coltotal  1.0  1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: MAUT2 2 cars
             0     1     2     3     4     5     6    7  rowtotal
0         0.94  0.94  0.94  0.94  0.94  0.95  0.89  1.0      0.94
1         0.06  0.06  0.06  0.06  0.06  0.05  0.11  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: MAUT0 No car
             0     1     2     3     4     5     6    7    8    9  rowtotal
0         0.92  0.94  0.93  0.95  0.98  0.98  0.94  1.0  1.0  1.0      0.94
1         0.08  0.06  0.07  0.05  0.02  0.02  0.06  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: National Health Service
             0    1     2     3     4     5     6     7     8     9  rowtotal
0         0.87  1.0  0.91  0.92  0.92  0.93  0.95  0.94  0.96  0.95      0.94
1         0.13  0.0  0.09  0.08  0.08  0.07  0.05  0.06  0.04  0.05      0.06
coltotal  1.00  1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Private health insurance
             0     1     2     3     4     5     6     7    8     9  rowtotal
0         0.95  0.96  0.94  0.95  0.93  0.92  0.92  0.91  1.0  0.87      0.94
1         0.05  0.04  0.06  0.05  0.07  0.08  0.08  0.09  0.0  0.13      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.00      1.00
**************************************************
**************************************************
feature/column: Income < 30.000
             0     1     2     3     4     5     6     7     8    9  rowtotal
0         0.92  0.91  0.92  0.95  0.96  0.97  0.97  0.96  0.98  1.0      0.94
1         0.08  0.09  0.08  0.05  0.04  0.03  0.03  0.04  0.02  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Income 30-45.000
             0     1     2     3     4     5     6     7     8    9  rowtotal
0         0.94  0.93  0.94  0.94  0.94  0.95  0.94  0.95  0.94  0.9      0.94
1         0.06  0.07  0.06  0.06  0.06  0.05  0.06  0.05  0.06  0.1      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Income 45-75.000
             0     1     2     3     4     5     6     7     8     9  rowtotal
0         0.96  0.96  0.96  0.93  0.91  0.92  0.91  0.92  0.94  0.96      0.94
1         0.04  0.04  0.04  0.07  0.09  0.08  0.09  0.08  0.06  0.04      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Income 75-122.000
             0     1     2     3    4    5    6    7    8     9  rowtotal
0         0.95  0.93  0.92  0.92  0.9  0.9  1.0  1.0  1.0  0.75      0.94
1         0.05  0.07  0.08  0.08  0.1  0.1  0.0  0.0  0.0  0.25      0.06
coltotal  1.00  1.00  1.00  1.00  1.0  1.0  1.0  1.0  1.0  1.00      1.00
**************************************************
**************************************************
feature/column: Income >123.000

             0     1     2     3    4    5    7    9  rowtotal
0         0.94  0.93  0.92  0.97  1.0  1.0  1.0  1.0      0.94
1         0.06  0.07  0.08  0.03  0.0  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.0  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Average income
            0     1     2     3     4    5     6     7     8    9  rowtotal
0         1.0  0.98  0.97  0.96  0.93  0.9  0.93  0.87  0.89  1.0      0.94
1         0.0  0.02  0.03  0.04  0.07  0.1  0.07  0.13  0.11  0.0      0.06
coltotal  1.0  1.00  1.00  1.00  1.00  1.0  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Purchasing power class
             1     2     3     4     5     6     7     8  rowtotal
0         0.97  0.96  0.95  0.95  0.95  0.93  0.86  0.92      0.94
1         0.03  0.04  0.05  0.05  0.05  0.07  0.14  0.08      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Contribution private third party insurance
             0     1     2     3  rowtotal
0         0.96  0.96  0.91  0.82      0.94
1         0.04  0.04  0.09  0.18      0.06
coltotal  1.00  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Contribution third party insurance (firms)
             0    1     2     3    4    5    6  rowtotal
0         0.94  1.0  0.93  0.87  1.0  1.0  1.0      0.94
1         0.06  0.0  0.07  0.13  0.0  0.0  0.0      0.06
coltotal  1.00  1.0  1.00  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution third party insurane (agriculture)
             0    2     3     4  rowtotal
0         0.94  1.0  0.96  0.98      0.94
1         0.06  0.0  0.04  0.02      0.06
coltotal  1.00  1.0  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Contribution car policies
             0    4     5     6    7    8  rowtotal
0         0.97  1.0  0.98  0.89  1.0  1.0      0.94
1         0.03  0.0  0.02  0.11  0.0  0.0      0.06
coltotal  1.00  1.0  1.00  1.00  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution delivery van policies
             0    5     6    7  rowtotal
0         0.94  1.0  0.94  1.0      0.94
1         0.06  0.0  0.06  0.0      0.06
coltotal  1.00  1.0  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution motorcycle/scooter policies
             0     3     4     5     6    7  rowtotal
0         0.94  0.33  0.93  0.88  0.98  1.0      0.94
1         0.06  0.67  0.07  0.12  0.02  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution lorry policies
             0    4    6    9  rowtotal
0         0.94  1.0  1.0  1.0      0.94
1         0.06  0.0  0.0  0.0      0.06
coltotal  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution trailer policies
             0     1     2    3    4    5  rowtotal
0         0.94  0.95  0.87  1.0  1.0  1.0      0.94
1         0.06  0.05  0.13  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution tractor policies
             0     3    4     5     6  rowtotal
0         0.94  0.97  1.0  0.93  0.89      0.94
1         0.06  0.03  0.0  0.07  0.11      0.06
coltotal  1.00  1.00  1.0  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Contribution agricultural machines policies
             0    2    3    4    6  rowtotal
0         0.94  1.0  1.0  1.0  1.0      0.94
1         0.06  0.0  0.0  0.0  0.0      0.06
coltotal  1.00  1.0  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution moped policies
             0     2     3    4     5    6  rowtotal
0         0.94  0.97  0.98  1.0  0.94  1.0      0.94
1         0.06  0.03  0.02  0.0  0.06  0.0      0.06
coltotal  1.00  1.00  1.00  1.0  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution life insurances
             0    1    2     3     4     5     6    7    8    9  rowtotal
0         0.94  1.0  1.0  0.93  0.88  0.89  0.95  1.0  1.0  1.0      0.94
1         0.06  0.0  0.0  0.07  0.12  0.11  0.05  0.0  0.0  0.0      0.06
coltotal  1.00  1.0  1.0  1.00  1.00  1.00  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution private accident insurance policies
             0    1     2    3    4    5    6  rowtotal
0         0.94  1.0  0.94  1.0  1.0  1.0  1.0      0.94
1         0.06  0.0  0.06  0.0  0.0  0.0  0.0      0.06
coltotal  1.00  1.0  1.00  1.0  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution family accidents insurance policies
             0     2     3  rowtotal
0         0.94  0.92  0.69      0.94
1         0.06  0.08  0.31      0.06
coltotal  1.00  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Contribution disability insurance policies
             0    4    5     6    7  rowtotal
0         0.94  1.0  1.0  0.79  1.0      0.94
1         0.06  0.0  0.0  0.21  0.0      0.06
coltotal  1.00  1.0  1.0  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution fire policies
             0     1     2     3     4     5     6    7    8  rowtotal
0         0.96  0.98  0.99  0.93  0.88  0.95  0.98  1.0  1.0      0.94
1         0.04  0.02  0.01  0.07  0.12  0.05  0.02  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution surfboard policies
             0    1    3  rowtotal
0         0.94  0.5  1.0      0.94
1         0.06  0.5  0.0      0.06
coltotal  1.00  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution boat policies
             0    1    2    3     4    5     6  rowtotal
0         0.94  0.4  0.6  0.6  0.69  1.0  0.33      0.94
1         0.06  0.6  0.4  0.4  0.31  0.0  0.67      0.06
coltotal  1.00  1.0  1.0  1.0  1.00  1.0  1.00      1.00
**************************************************
**************************************************
feature/column: Contribution bicycle policies
             0    1  rowtotal
0         0.94  0.9      0.94
1         0.06  0.1      0.06
coltotal  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution property insurance policies
             0     1     2    3    4    5    6  rowtotal
0         0.94  0.83  0.88  1.0  1.0  1.0  1.0      0.94
1         0.06  0.17  0.12  0.0  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.0  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Contribution social security insurance policies
             0     2     3     4    5  rowtotal
0         0.94  0.73  0.82  0.82  1.0      0.94
1         0.06  0.27  0.18  0.18  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Number of private third party insurance

             0     1    2  rowtotal
0         0.96  0.91  1.0      0.94
1         0.04  0.09  0.0      0.06
coltotal  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Number of third party insurance (firms)
             0     1    5  rowtotal
0         0.94  0.94  1.0      0.94
1         0.06  0.06  0.0      0.06
coltotal  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Number of third party insurane (agriculture)
             0     1  rowtotal
0         0.94  0.98      0.94
1         0.06  0.02      0.06
coltotal  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Number of car policies
             0     1     2     3    4    6    7  rowtotal
0         0.97  0.91  0.85  0.92  1.0  1.0  1.0      0.94
1         0.03  0.09  0.15  0.08  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Number of delivery van policies
             0     1    2    3    4  rowtotal
0         0.94  0.95  1.0  1.0  1.0      0.94
1         0.06  0.05  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Number of motorcycle/scooter policies
             0     1    2    8  rowtotal
0         0.94  0.93  0.9  1.0      0.94
1         0.06  0.07  0.1  0.0      0.06
coltotal  1.00  1.00  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Number of lorry policies
             0    1    2    3  rowtotal
0         0.94  1.0  1.0  1.0      0.94
1         0.06  0.0  0.0  0.0      0.06
coltotal  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Number of trailer policies
             0    1    2    3  rowtotal
0         0.94  0.9  1.0  1.0      0.94
1         0.06  0.1  0.0  0.0      0.06
coltotal  1.00  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Number of tractor policies
             0     1     2    3    4  rowtotal
0         0.94  0.96  0.97  1.0  1.0      0.94
1         0.06  0.04  0.03  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Number of agricultural machines policies
             0    1    2    3    6  rowtotal
0         0.94  1.0  1.0  1.0  1.0      0.94
1         0.06  0.0  0.0  0.0  0.0      0.06
coltotal  1.00  1.0  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Number of moped policies
             0     1    2  rowtotal
0         0.94  0.98  1.0      0.94
1         0.06  0.02  0.0      0.06
coltotal  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Number of life insurances
             0     1    2     3     4    8  rowtotal
0         0.94  0.95  0.9  0.82  0.62  1.0      0.94
1         0.06  0.05  0.1  0.18  0.38  0.0      0.06
coltotal  1.00  1.00  1.0  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Number of private accident insurance policies
             0     1  rowtotal
0         0.94  0.97      0.94
1         0.06  0.03      0.06
coltotal  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Number of family accidents insurance policies
             0     1  rowtotal
0         0.94  0.84      0.94
1         0.06  0.16      0.06
coltotal  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Number of disability insurance policies
             0     1    2  rowtotal
0         0.94  0.79  1.0      0.94
1         0.06  0.21  0.0      0.06
coltotal  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Number of fire policies
             0     1     2    3    4    5    7  rowtotal
0         0.96  0.92  0.94  1.0  1.0  1.0  1.0      0.94
1         0.04  0.08  0.06  0.0  0.0  0.0  0.0      0.06
coltotal  1.00  1.00  1.00  1.0  1.0  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: Number of surfboard policies
             0     1  rowtotal
0         0.94  0.67      0.94
1         0.06  0.33      0.06
coltotal  1.00  1.00      1.00
**************************************************
**************************************************
feature/column: Number of boat policies
             0     1    2  rowtotal
0         0.94  0.61  0.5      0.94
1         0.06  0.39  0.5      0.06
coltotal  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Number of bicycle policies
             0     1     2    3  rowtotal
0         0.94  0.91  0.88  0.5      0.94
1         0.06  0.09  0.12  0.5      0.06
coltotal  1.00  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Number of property insurance policies
             0     1    2  rowtotal
0         0.94  0.89  1.0      0.94
1         0.06  0.11  0.0      0.06
coltotal  1.00  1.00  1.0      1.00
**************************************************
**************************************************
feature/column: Number of social security insurance policies
             0    1    2  rowtotal
0         0.94  0.8  1.0      0.94
1         0.06  0.2  0.0      0.06
coltotal  1.00  1.0  1.0      1.00
**************************************************
**************************************************
feature/column: CARAVAN Number of mobile home policies
            0    1  rowtotal
0         1.0  0.0      0.94
1         0.0  1.0      0.06
coltotal  1.0  1.0      1.00
**************************************************

Drop columns with no significant contribution to y

In [13]:
drop_cols= ["Number of houses", "Avg size household", 
            "Avg age", "Roman catholic", 
            "Protestant", "Other religion", "No religion", 
            "Married", "Living together", 
            "Other relation", "Singles", 
            "Household without children", "Household with children",
           "Entrepreneur", "Farmer", 
            "Social class B2", "Social class D", 
            "Rented house", "Home owners", "MAUT1 1 car", 
            "MAUT0 No car", "Income < 30.000", "Income 30-45.000", "Income 45-75.000", "Income >123.000", 
            "Contribution third party insurane (agriculture)", "Contribution delivery van policies", 
            "Contribution lorry policies", "Contribution agricultural machines policies", "Contribution moped policies", 
            "Contribution private accident insurance policies", 
            "Contribution bicycle policies", "Number of private third party insurance", 
            "Number of third party insurance (firms)", "Number of third party insurane (agriculture)",
            "Number of delivery van policies", "Number of motorcycle/scooter policies",
            "Number of lorry policies", "Number of trailer policies", "Number of tractor policies",
            "Number of agricultural machines policies", "Number of agricultural machines policies",
            "Number of moped policies", "Number of private accident insurance policies", 
            "Number of fire policies"]
all_data = all_data.drop(drop_cols, axis=1)

Ceate features from columns. for any class within a feature that appears to contribute significantly to prediction of y, are combined. threshold used was >=0.1 towards 1

In [14]:
def create_features(data, info):
    for col, col_info in info.items():
        for name in col_info:
            values = col_info[name]
            data[col+name] = data[col].isin(values).astype(int)
        data = data.drop(col, axis=1)
    return data

In [15]:
# Encode these columns
info = {
    "Customer Subtype": {"1": ["8"]},
    "Customer main type": {"1": ["2"]},
    "High level education": {"1":["4","5","6","7","9"]},
    "Medium level education": {"1":["7"]},
    "Lower level education": {"1": ["1"]},
    "High status": {"1":["6", "7", "8"]},
    "Middle management":{"1":["7"]},
    "Skilled labourers": {"1": ["8"]},
    "Unskilled labourers": {"1": ["8"]},
    "Social class A": {"1": ["4", "5", "6", "7"]},
    "Social class B1": {"1": ["6", "8"]},
    "Social class C": {"1": ["8", "9"]},
    "MAUT2 2 cars": {"1": ["6"]},
    "National Health Service": {"1": ["0"]},
    "Income 75-122.000": {"1": ["9"]}, #
    "Private health insurance": {"1": ["9"]},
    "Average income": {"1": ["7", "8"]},
    "Purchasing power class": {"1": ["7"]},
    "Contribution private third party insurance": {"1": ["3"]},
    "Contribution third party insurance (firms)": {"1": ["3"]},
    "Contribution car policies": {"1": ["6"]},
    "Contribution motorcycle/scooter policies" : {"1": ["3", "5"]}, #3 = .33
    "Contribution tractor policies": {"1": ["6"]},
    "Contribution trailer policies" : {"1": ["2"]},
    "Contribution life insurances" : {"1": ["4", "5"]},
    "Contribution family accidents insurance policies" : {"1": ["3"]}, #
    "Contribution disability insurance policies" : {"1": ["6"]}, #
    "Contribution fire policies" : {"1": ["4"]},
    "Contribution surfboard policies": {"1": ["1"]}, #
    "Contribution boat policies": {"1": ["1", "2", "3", "4", "6"]}, #    
    "Contribution property insurance policies": {"1": ["1",  "2"]}, #   
    "Contribution social security insurance policies": {"1": ["2", "3", "4"]}, #
    "Number of car policies": {"1": ["2"]},    #
    "Number of life insurances": {"1": ["1"]},  #  
    "Number of family accidents insurance policies": {"1": ["1"]},    
    "Number of disability insurance policies": {"1": ["1"]},    
    "Number of surfboard policies": {"1": ["1"]},  #  
    "Number of boat policies": {"1": ["1", "2"]}, #   
    "Number of bicycle policies": {"1": ["2", "3"]}, #    
    "Number of property insurance policies": {"1": ["1"]}, 
    "Number of social security insurance policies": {"1": ["1"]}
          }
all_data = create_features(all_data, info)

In [16]:
#all_data.columns

In [17]:
#all_data

### Preparing dataset for training

In [18]:
target='CARAVAN Number of mobile home policies'
train_data = all_data[all_data['data']=='train']

# splitting back the train and test datasets
X = train_data.drop([target,'data'],1)
y = train_data[target]
x_test = all_data.drop([target,'data'],1)[all_data['data']=='test']

# Divide the training data given to train and validation data frames
x_train, x_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

### Storing processed data

In [19]:
x_train.to_csv('data/processed_data/x_train.csv',index=False)
x_val.to_csv('data/processed_data/x_val.csv',index=False)
y_train.to_csv('data/processed_data/y_train.csv',index=False)
y_val.to_csv('data/processed_data/y_val.csv',index=False)
x_test.to_csv('data/processed_data/x_test.csv',index=False)